### PR TITLE
Added print-catches and delete-all-catches

### PR DESCRIPTION
**Pull request by leathekd**
For symmetry.

I have corresponding changes for swank-clojure that I'll send if you find these acceptable.

### CODE REVIEW

**Comment by GeorgeJahad** [comment]
Hey David, thanks for the addition.  The code looks fine, but in this repo, I only pull from those who've signed a Clojure CA.  Would you consider doing that?

**Comment by leathekd** [comment]
Sure, will do.

**Comment by leathekd** [comment]
A friend handed in my CA at Clojure/West.  I don't know when the contributors web page will be updated, though.

**Comment by GeorgeJahad** [comment]
Thanks David!

**Pull request merged**
